apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ums7
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-ums7@sha256:1a771183bf841dad038a0d0fa2d6c891b3b399e1bef21e78bccbf5a59aae7519
        name: my-nodejs
        resources: {}
status: {}
